name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run ESLint check
        run: eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run Prettier check
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check
