name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm ci
      - name: Run ESLint check
        run: npm run eslint:check
      - name: Run Prettier check
        run: npm run prettier:check
